- name: Michael Sarahan
  email: msarahan@gmail.com
  github: msarahan
  alternate_emails:
  - msarahan@continuum.io
  - msarahan@anaconda.com
  aliases:
  - Mike Sarahan
  num_commits: 98
  first_commit: 2019-01-03 20:00:40
- name: Nehal J Wani
  email: nehaljw.kkd1@gmail.com
  num_commits: 4
  first_commit: 2019-05-01 08:25:27
  github: nehaljwani
- name: Jonathan J. Helmus
  email: jjhelmus@gmail.com
  num_commits: 10
  first_commit: 2019-08-02 14:19:54
  github: jjhelmus
- name: Alan Du
  email: alanhdu@gmail.com
  num_commits: 4
  first_commit: 2019-11-07 05:49:27
  github: alanhdu
- name: Ray Donnelly
  email: mingw.android@gmail.com
  num_commits: 14
  first_commit: 2020-05-06 10:49:55
  github: mingwandroid
- name: ossdev07
  email: ossdev@puresoftware.com
  num_commits: 1
  first_commit: 2020-01-06 10:18:31
  github: ossdev07
- name: leej3
  email: johnleenimh@gmail.com
  num_commits: 12
  first_commit: 2021-02-23 12:20:16
  github: leej3
- name: Matthew R. Becker
  email: beckermr@users.noreply.github.com
  num_commits: 2
  first_commit: 2020-12-29 14:58:11
  github: beckermr
- name: Eli Uriegas
  email: seemethere101@gmail.com
  num_commits: 1
  first_commit: 2021-03-14 08:41:18
  github: seemethere
