# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
matrix:
  include:
    - python: 2.7
    - arch: amd64
      python: 3.7
    - arch: arm64
      python: 3.7
env:
  global:
    - SUDO=""
    - CONDA_ALWAYS_YES=1
install:
  - set -e
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      set -x;
      # Archiconda install requires sudo for running commands. Pass the path
      # through to the sudo environment so that condda is accessible
      SUDO='sudo env PATH=$PATH'
      wget -q "https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh" -O archiconda.sh;
      chmod +x archiconda.sh;
      bash archiconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      $SUDO conda install python=3.7 conda conda-build;
      set +x;
    else
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.7.5-linux-64.exe -O conda.exe;
      chmod +x conda.exe;
      ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build;
    fi;
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install futures mock pytest-cov pytest-mock;
    else
      pip3 install mock pytest-cov pytest-mock;
    fi;
  - $SUDO conda build conda.recipe --no-test
  - $SUDO conda install --use-local conda-package-handling
  - $SUDO conda info -a
script:
  # rebuilding the recipe with our new CPH installed tests it a bit deeper than the test suite.
  - which conda
  - $SUDO conda build conda.recipe
  # the system pytest is used for coverage testing, cph from current conda envorinment is used.
  - which pytest
  - pytest -v --color=yes -rA --cov=conda_package_handling tests
after_success:
  - $SUDO conda install codecov
  - codecov
